//! SAW script emission for the `gen-verify-rust` subcommand.
//!
//! Extracted from `gen_verify_rust.rs` to stay under the 500-line limit
//! while adding sret, aggregate return, range-precondition, and
//! buffer-override support.

use crate::buffer_overrides::BufferOverrides;
use crate::constraints::TypeInfo;
use crate::saw_emit::cryptol_bridge::{cryptol_arg_for, AbiReturnBridge};
use std::collections::HashMap;

/// A single named variant with its discriminant value.
#[derive(Debug, Clone)]
pub struct Variant {
    pub name: String,
    pub discriminant: u64,
}

/// Parsed `--variant-map` entries for one or more parameters.
///
/// Format: `PARAM=Variant1:disc1,Variant2:disc2,...`
#[derive(Debug, Clone, Default)]
pub struct VariantMap {
    /// param name → list of reachable variants
    pub entries: HashMap<String, Vec<Variant>>,
}

impl VariantMap {
    /// Parse all `--variant-map` CLI values.
    pub fn parse_all(raw: &[String]) -> anyhow::Result<Self> {
        let mut entries = HashMap::new();
        for s in raw {
            let (param, rest) = s.split_once('=').ok_or_else(|| {
                anyhow::anyhow!("--variant-map: expected PARAM=V1:D1,V2:D2,..., got '{s}'")
            })?;
            let mut variants = Vec::new();
            for pair in rest.split(',') {
                let pair = pair.trim();
                if pair.is_empty() {
                    continue;
                }
                let (vname, disc_s) = pair
                    .split_once(':')
                    .ok_or_else(|| anyhow::anyhow!("--variant-map: expected V:D in '{pair}'"))?;
                let disc: u64 = disc_s.parse().map_err(|_| {
                    anyhow::anyhow!("--variant-map: discriminant '{disc_s}' is not a u64")
                })?;
                variants.push(Variant {
                    name: vname.to_string(),
                    discriminant: disc,
                });
            }
            if variants.is_empty() {
                anyhow::bail!("--variant-map: no variants for param '{param}'");
            }
            entries.insert(param.to_string(), variants);
        }
        Ok(Self { entries })
    }

    /// Whether there are any variant restrictions.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// How the target function returns its result at the LLVM ABI level.
#[derive(Debug, Clone)]
pub enum RustReturnKind {
    /// Scalar `iN` return (the common case for Rust decision fns).
    Scalar { bits: u32 },
    /// sret: the function is `void`-returning and uses the first
    /// parameter as a pointer to a struct that receives the result.
    /// `llvm_type` is the raw LLVM struct name (e.g. `%struct.Pair`).
    Sret {
        llvm_type: String,
        size_bytes: usize,
    },
    /// Aggregate return: `{ i1, i1 }`, `{ i8, i32 }`, etc.
    /// Each entry is the bit-width of one field.
    Aggregate { field_bits: Vec<u32> },
}

/// A single parameter to verify.
#[derive(Debug, Clone)]
pub struct RustVerifyParam {
    pub index: usize,
    pub name: String,
    pub bits: u32,
    pub llvm_type: String,
    /// Optional `range(lo, hi)` constraint from LLVM IR attributes.
    pub range: Option<(u64, u64)>,
}

/// Everything the SAW + meta emitters need about the resolved target.
#[derive(Debug)]
pub struct RustVerifyArtifacts {
    pub mangled_name: String,
    pub params: Vec<RustVerifyParam>,
    pub return_kind: RustReturnKind,
    pub return_llvm_type: String,
    pub globals: Vec<String>,
}

impl RustVerifyArtifacts {
    pub fn return_bits(&self) -> u32 {
        match &self.return_kind {
            RustReturnKind::Scalar { bits } => *bits,
            RustReturnKind::Sret { size_bytes, .. } => (*size_bytes as u32) * 8,
            RustReturnKind::Aggregate { field_bits } => field_bits.iter().sum(),
        }
    }
}

#[allow(clippy::too_many_arguments)]
pub fn emit_saw_script(
    function: &str,
    cryptol_fn: &str,
    bc_name: &str,
    cry_name: &str,
    arts: &RustVerifyArtifacts,
    overrides: &BufferOverrides,
    variant_map: &VariantMap,
    uninterpreted: &crate::uninterpreted::UninterpretedBlock,
) -> String {
    let mut buf = String::new();
    buf.push_str(&format!(
        "// Auto-generated by `saw-spec-gen gen-verify-rust`.\n\
         // Prove that the Rust {function} (compiled to LLVM bitcode by rustc)\n\
         // is extensionally equal to the Cryptol spec {cryptol_fn}.\n\
         //\n\
         // Mangled symbol resolved from the .ll: {mangled}\n\n\
         m <- llvm_load_module \"{bc_name}\";\n\n\
         import \"{cry_name}\";\n\n",
        mangled = arts.mangled_name,
    ));
    // Uninterpreted-primitive contracts bound via `llvm_unsafe_assume_spec`.
    if !uninterpreted.is_empty() {
        buf.push_str("// Uninterpreted primitive contracts\n");
        buf.push_str(&uninterpreted.snippet);
        buf.push('\n');
    }
    buf.push_str(&format!("let {function}_equiv_spec = do {{\n"));

    // Globals
    for g in &arts.globals {
        buf.push_str(&format!(
            "    llvm_alloc_global \"{g}\";\n\
             \x20   llvm_points_to (llvm_global \"{g}\") \
             (llvm_global_initializer \"{g}\");\n"
        ));
    }

    // sret allocation
    let sret_ptr_name = "result_ptr";
    if let RustReturnKind::Sret {
        llvm_type,
        size_bytes,
    } = &arts.return_kind
    {
        buf.push_str(&format!(
            "    {sret_ptr_name} <- llvm_alloc (llvm_alias \"{llvm_type}\");\n"
        ));
        let _ = size_bytes; // used later for meta; SAW resolves size from alias
    }

    // Parameters: fresh vars + buffer overrides
    let mut cry_args = Vec::new();
    let mut exec_args = Vec::new();

    // sret pointer goes first in execute_func args
    if matches!(&arts.return_kind, RustReturnKind::Sret { .. }) {
        exec_args.push(format!("llvm_term {sret_ptr_name}"));
    }

    for p in &arts.params {
        if let Some(saw_ty) = overrides.override_saw_type(&p.name) {
            // Buffer override param
            let var_name = overrides.value_var_for(&p.name);
            let is_out = overrides.is_out_buffer(&p.name);
            if is_out {
                buf.push_str(&format!(
                    "    {name}_ptr <- llvm_alloc ({saw_ty});\n\
                     \x20   {var_name} <- llvm_fresh_var \"{var_name}\" ({saw_ty});\n\
                     \x20   llvm_points_to {name}_ptr (llvm_term {var_name});\n",
                    name = p.name,
                ));
            } else {
                buf.push_str(&format!(
                    "    {name}_ptr <- llvm_alloc_readonly ({saw_ty});\n\
                     \x20   {name} <- llvm_fresh_var \"{name}\" ({saw_ty});\n\
                     \x20   llvm_points_to {name}_ptr (llvm_term {name});\n",
                    name = p.name,
                ));
            }
            cry_args.push(overrides.value_var_for(&p.name));
            exec_args.push(format!("{}_ptr", p.name));
        } else {
            buf.push_str(&format!(
                "    {name} <- llvm_fresh_var \"{name}\" (llvm_int {bits});\n",
                name = p.name,
                bits = p.bits,
            ));
            cry_args.push(p.name.clone());
            exec_args.push(format!("llvm_term {}", p.name));
        }
    }

    // Range preconditions
    for p in &arts.params {
        if let Some((lo, hi)) = p.range {
            if lo == 0 && hi > 0 {
                buf.push_str(&format!(
                    "    llvm_precond {{{{ {name} <= ({max} : [{bits}]) }}}};\n",
                    name = p.name,
                    max = hi - 1,
                    bits = p.bits,
                ));
            }
        }
    }

    // Variant-map membership preconditions
    for p in &arts.params {
        if let Some(variants) = variant_map.entries.get(&p.name) {
            let clauses: Vec<String> = variants
                .iter()
                .map(|v| {
                    format!(
                        "{name} == ({disc} : [{bits}])",
                        name = p.name,
                        disc = v.discriminant,
                        bits = p.bits
                    )
                })
                .collect();
            let joined = clauses.join(" \\/ ");
            buf.push_str(&format!("    llvm_precond {{{{ {joined} }}}};\n",));
        }
    }

    // Max-len preconditions from buffer overrides
    for (name, val) in overrides.max_len_preconds_ordered() {
        if let Some(p) = arts.params.iter().find(|p| p.name == *name) {
            buf.push_str(&format!(
                "    llvm_precond {{{{ {name} <= ({val} : [{bits}]) }}}};\n",
                name = p.name,
                bits = p.bits,
            ));
        }
    }

    if let Some(pre_fn) = overrides.cryptol_fn_pre() {
        let pre_args = overrides
            .cryptol_call_args(pre_fn)
            .unwrap_or_else(|| cry_args.clone());
        let args_str = pre_args.join(" ");
        if args_str.is_empty() {
            buf.push_str(&format!("    llvm_precond {{{{ {pre_fn} }}}};\n"));
        } else {
            buf.push_str(&format!(
                "    llvm_precond {{{{ {pre_fn} {args_str} }}}};\n"
            ));
        }
    }

    // llvm_execute_func
    let exec_str = exec_args.join(", ");
    buf.push_str(&format!("    llvm_execute_func [{exec_str}];\n"));

    // Postconditions: out-buffer points_to
    for (out_name, cry_fn) in overrides.out_buffer_fns() {
        let post_args = overrides
            .cryptol_call_args(cry_fn)
            .unwrap_or_else(|| cry_args.clone());
        let args_str = post_args.join(" ");
        buf.push_str(&format!(
            "    llvm_points_to {out_name}_ptr \
             (llvm_term {{{{ {cry_fn} {args_str} }}}});\n",
        ));
    }

    // Return assertion
    emit_return_assertion(&mut buf, cryptol_fn, &cry_args, arts, variant_map);

    buf.push_str("};\n\n");

    // Proof markers + verify
    let ov_list = uninterpreted.override_names.join(", ");
    buf.push_str(&format!(
        "print \"BEGIN_PROOF {function}\";\n\
         llvm_verify m \"{}\" [{}] true {}_equiv_spec z3;\n\
         print \"PROVED {function}\";\n\
         print \"VERIFIED\";\n",
        arts.mangled_name, ov_list, function,
    ));
    buf
}

fn emit_return_assertion(
    buf: &mut String,
    cryptol_fn: &str,
    cry_args: &[String],
    arts: &RustVerifyArtifacts,
    variant_map: &VariantMap,
) {
    let cry_call = build_cryptol_call(cryptol_fn, cry_args, &arts.params);

    // If a variant-map entry exists for "return", use VariantRemap
    // bridge to compose discriminant mapping with any width bridge
    // needed for niche-packed enums.
    if let Some(variants) = variant_map.entries.get("return") {
        let ret_bits = arts.return_bits();
        let variant_pairs: Vec<(u64, u64)> = variants
            .iter()
            .map(|v| (v.discriminant, v.discriminant))
            .collect();
        let bridge = AbiReturnBridge::VariantRemap {
            variants: variant_pairs,
            abi_bits: ret_bits,
            inner: None,
        };
        let wrapped = bridge.wrap(&cry_call);
        buf.push_str(&format!(
            "    llvm_return (llvm_term {{{{ {wrapped} }}}});\n"
        ));
        return;
    }

    match &arts.return_kind {
        RustReturnKind::Scalar { .. } => {
            buf.push_str(&format!(
                "    llvm_return (llvm_term {{{{ {cry_call} }}}});\n"
            ));
        }
        RustReturnKind::Sret { .. } => {
            buf.push_str(&format!(
                "    llvm_points_to result_ptr \
                 (llvm_term {{{{ {cry_call} }}}});\n"
            ));
        }
        RustReturnKind::Aggregate { field_bits } => {
            let bridge = AbiReturnBridge::StructValue {
                field_bits: field_bits.clone(),
            };
            buf.push_str(&bridge.emit_saw_return(&cry_call));
        }
    }
}

fn build_cryptol_call(cryptol_fn: &str, cry_args: &[String], params: &[RustVerifyParam]) -> String {
    if cry_args.is_empty() {
        return cryptol_fn.to_string();
    }
    let args = cry_args
        .iter()
        .zip(params.iter())
        .map(|(name, p)| cryptol_arg_for(name, &bits_to_typeinfo(p.bits)))
        .collect::<Vec<_>>()
        .join(" ");
    format!("{cryptol_fn} {args}")
}

pub fn bits_to_typeinfo(bits: u32) -> TypeInfo {
    match bits {
        1 => TypeInfo::Bool,
        n => TypeInfo::UnsignedInt(n),
    }
}
