//! Emit SAW verification scripts from derived constraints.
//!
//! Generates .saw files that can be loaded by SAW to create override
//! specs for unspecified functions. Supports both LLVM and MIR verify modes.

use crate::clang_ast::InterfaceMethod;
use crate::constraints::*;
use anyhow::{Context, Result};
use std::fs;
use std::io::Write;
use std::path::Path;

/// Whether to emit LLVM or MIR specs.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum EmitMode {
    Llvm,
    Mir,
}

/// Emit SAW spec files for all constraints.
pub fn emit_saw_specs(specs: &[SpecConstraint], output_dir: &Path) -> Result<()> {
    emit_saw_specs_with_mode(specs, output_dir, EmitMode::Llvm)
}

/// Emit MIR SAW spec files for all constraints.
pub fn emit_mir_saw_specs(specs: &[SpecConstraint], output_dir: &Path) -> Result<()> {
    emit_saw_specs_with_mode(specs, output_dir, EmitMode::Mir)
}

fn emit_saw_specs_with_mode(
    specs: &[SpecConstraint],
    output_dir: &Path,
    mode: EmitMode,
) -> Result<()> {
    fs::create_dir_all(output_dir)
        .with_context(|| format!("Failed to create output directory {}", output_dir.display()))?;

    for spec in specs {
        let filename = format!("{}_auto_spec.saw", sanitize_name(&spec.function_name));
        let filepath = output_dir.join(&filename);
        let mut file = fs::File::create(&filepath)
            .with_context(|| format!("Failed to create {}", filepath.display()))?;

        let content = match mode {
            EmitMode::Llvm => generate_saw_spec(spec),
            EmitMode::Mir => generate_mir_spec(spec),
        };
        write!(file, "{}", content)?;
    }

    // Generate an index file that includes all specs
    let index_path = output_dir.join("auto_specs.saw");
    let mut index = fs::File::create(&index_path)?;
    writeln!(index, "// Auto-generated SAW specs -- do not edit")?;
    writeln!(
        index,
        "// Generated by saw-spec-gen from type system constraints"
    )?;
    writeln!(
        index,
        "// Mode: {}",
        match mode {
            EmitMode::Llvm => "LLVM",
            EmitMode::Mir => "MIR",
        }
    )?;
    writeln!(index)?;
    for spec in specs {
        let filename = format!("{}_auto_spec.saw", sanitize_name(&spec.function_name));
        writeln!(index, "include \"{filename}\";")?;
    }

    Ok(())
}

fn generate_saw_spec(spec: &SpecConstraint) -> String {
    let mut out = String::new();
    let fn_name = &spec.function_name;
    let target_name = spec
        .mangled_name
        .as_deref()
        .unwrap_or(&spec.function_name);

    out.push_str(&format!("// Auto-generated spec for: {fn_name}\n"));
    out.push_str("// Constraints derived from type system and annotations\n");
    if spec.can_throw {
        out.push_str("// WARNING: Function may throw -- exception path not modeled\n");
    }
    out.push_str(&format!(
        "\nlet {safe_name}_auto_spec : LLVMSetup () = do {{\n",
        safe_name = sanitize_name(fn_name),
    ));

    // Emit parameter setup
    for param in &spec.params {
        out.push_str(&format!("\n    // Parameter: {}\n", param.name));

        match param.alloc_type {
            AllocType::AllocReadonly => {
                out.push_str(&format!(
                    "    {name}_ptr <- llvm_alloc_readonly ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    {name}_before <- llvm_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    llvm_points_to {name}_ptr (llvm_term {name}_before);\n",
                    name = param.name,
                ));
            }
            AllocType::AllocMutable => {
                out.push_str(&format!(
                    "    {name}_ptr <- llvm_alloc ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    {name}_val <- llvm_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    llvm_points_to {name}_ptr (llvm_term {name}_val);\n",
                    name = param.name,
                ));
            }
            AllocType::FreshVar => {
                out.push_str(&format!(
                    "    {name} <- llvm_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
            }
        }

        for pre in &param.preconditions {
            out.push_str(&format!("    {pre};\n"));
        }
    }

    // Emit execute_func
    let args: Vec<String> = spec
        .params
        .iter()
        .map(|p| match p.alloc_type {
            AllocType::AllocReadonly | AllocType::AllocMutable => format!("{}_ptr", p.name),
            AllocType::FreshVar => format!("llvm_term {}", p.name),
        })
        .collect();
    out.push_str(&format!(
        "\n    llvm_execute_func [{}];\n",
        args.join(", ")
    ));

    // Emit return value
    if spec.return_constraint.saw_type != "// void" {
        out.push_str(&format!(
            "\n    ret <- llvm_fresh_var \"ret\" ({});\n",
            spec.return_constraint.saw_type,
        ));
        for vc in &spec.return_constraint.value_constraints {
            out.push_str(&format!("    {vc};\n"));
        }
        out.push_str("    llvm_return (llvm_term ret);\n");
    }

    // Emit postconditions (readonly params unchanged)
    if !spec.postconditions.is_empty() {
        out.push_str("\n    // Postconditions\n");
        for post in &spec.postconditions {
            out.push_str(&format!("    {post};\n"));
        }
    }

    out.push_str("};\n");

    // Add the assume_spec call
    out.push_str(&format!(
        "\n// Usage: ov_{safe} <- llvm_unsafe_assume_spec m \"{target}\" {safe}_auto_spec;\n",
        safe = sanitize_name(fn_name),
        target = target_name,
    ));

    out
}

fn generate_mir_spec(spec: &SpecConstraint) -> String {
    let mut out = String::new();
    let fn_name = &spec.function_name;

    out.push_str(&format!("// Auto-generated MIR spec for: {fn_name}\n"));
    out.push_str("// Constraints derived from Rust type system\n");
    out.push_str(&format!(
        "\nlet {safe_name}_auto_spec : MIRSetup () = do {{\n",
        safe_name = sanitize_name(fn_name),
    ));

    // Emit parameter setup using MIR commands
    for param in &spec.params {
        out.push_str(&format!("\n    // Parameter: {}\n", param.name));

        match param.alloc_type {
            AllocType::AllocReadonly => {
                out.push_str(&format!(
                    "    {name}_ref <- mir_alloc_readonly (mir_find_adt m \"{ty}\");\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    {name}_before <- mir_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = mir_saw_type(&param.saw_type),
                ));
                out.push_str(&format!(
                    "    mir_points_to {name}_ref (mir_term {name}_before);\n",
                    name = param.name,
                ));
            }
            AllocType::AllocMutable => {
                out.push_str(&format!(
                    "    {name}_ref <- mir_alloc (mir_find_adt m \"{ty}\");\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    {name}_val <- mir_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = mir_saw_type(&param.saw_type),
                ));
                out.push_str(&format!(
                    "    mir_points_to {name}_ref (mir_term {name}_val);\n",
                    name = param.name,
                ));
            }
            AllocType::FreshVar => {
                out.push_str(&format!(
                    "    {name} <- mir_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = mir_saw_type(&param.saw_type),
                ));
            }
        }

        for pre in &param.preconditions {
            let mir_pre = pre
                .replace("llvm_precond", "mir_precond")
                .replace("llvm_", "mir_");
            out.push_str(&format!("    {mir_pre};\n"));
        }
    }

    // Emit execute_func
    let args: Vec<String> = spec
        .params
        .iter()
        .map(|p| match p.alloc_type {
            AllocType::AllocReadonly | AllocType::AllocMutable => format!("{}_ref", p.name),
            AllocType::FreshVar => format!("mir_term {}", p.name),
        })
        .collect();
    out.push_str(&format!(
        "\n    mir_execute_func [{}];\n",
        args.join(", ")
    ));

    // Emit return value
    if spec.return_constraint.saw_type != "// void" {
        out.push_str(&format!(
            "\n    ret <- mir_fresh_var \"ret\" ({});\n",
            mir_saw_type(&spec.return_constraint.saw_type),
        ));
        for vc in &spec.return_constraint.value_constraints {
            let mir_vc = vc
                .replace("llvm_postcond", "mir_postcond")
                .replace("llvm_", "mir_");
            out.push_str(&format!("    {mir_vc};\n"));
        }
        out.push_str("    mir_return (mir_term ret);\n");
    }

    // Emit postconditions
    if !spec.postconditions.is_empty() {
        out.push_str("\n    // Postconditions\n");
        for post in &spec.postconditions {
            let mir_post = post
                .replace("llvm_points_to", "mir_points_to")
                .replace("llvm_term", "mir_term");
            out.push_str(&format!("    {mir_post};\n"));
        }
    }

    out.push_str("};\n");

    // Add the assume_spec call
    out.push_str(&format!(
        "\n// Usage: ov_{safe} <- mir_unsafe_assume_spec m \"{target}\" {safe}_auto_spec;\n",
        safe = sanitize_name(fn_name),
        target = fn_name,
    ));

    out
}

/// Map LLVM SAW type syntax to MIR type syntax.
fn mir_saw_type(llvm_type: &str) -> String {
    if llvm_type.starts_with("llvm_int ") {
        let bits = llvm_type.trim_start_matches("llvm_int ");
        format!("mir_u{bits}")
    } else if llvm_type.starts_with("llvm_array ") {
        llvm_type
            .replace("llvm_array", "mir_array")
            .replace("llvm_int", "mir_u")
    } else if llvm_type.starts_with("llvm_alias ") {
        let name = llvm_type
            .trim_start_matches("llvm_alias \"")
            .trim_end_matches('"');
        format!("mir_find_adt m \"{name}\"")
    } else {
        llvm_type.to_string()
    }
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

// ============================================================================
// Interface stub + havoc spec generation
// ============================================================================

/// Emit vtable resolution stubs and havoc SAW specs for virtual methods.
///
/// Generates:
/// - `vtable_stubs.c`: C file with stub functions + concrete vtable globals per class
/// - `*_havoc_spec.saw`: SAW havoc specs where mutable memory is explicitly havoced
/// - `interface_overrides.saw`: Override setup + helper to allocate `this` with vtable wired
pub fn emit_interface_stubs(
    methods: &[InterfaceMethod],
    output_dir: &Path,
) -> Result<()> {
    if methods.is_empty() {
        return Ok(());
    }

    fs::create_dir_all(output_dir)
        .with_context(|| format!("Failed to create {}", output_dir.display()))?;

    // Group methods by class for vtable generation
    let mut by_class: std::collections::BTreeMap<String, Vec<&InterfaceMethod>> =
        std::collections::BTreeMap::new();
    for method in methods {
        by_class
            .entry(method.class_name.clone())
            .or_default()
            .push(method);
    }

    // Generate the LLVM IR stub file (vtable_stubs.ll) — no C compiler needed
    let ll_path = output_dir.join("vtable_stubs.ll");
    let ll_content = generate_llvm_ir_stubs(&by_class);
    fs::write(&ll_path, &ll_content)
        .with_context(|| format!("Failed to write {}", ll_path.display()))?;

    // Generate havoc SAW specs for each method
    for method in methods {
        let filename = format!(
            "{}_{}_havoc_spec.saw",
            sanitize_name(&method.class_name),
            sanitize_name(&method.method.name),
        );
        let filepath = output_dir.join(&filename);
        let content = generate_havoc_spec(method);
        fs::write(&filepath, content)?;
    }

    // Generate the index/override file with vtable helpers
    let index_path = output_dir.join("interface_overrides.saw");
    let index_content = generate_override_index_with_vtable(methods, &by_class);
    fs::write(&index_path, index_content)?;

    Ok(())
}

/// Generate LLVM IR text (.ll) with stub functions and vtable globals.
///
/// This is directly loadable by SAW via `llvm_load_module "vtable_stubs.ll"`
/// or assembleable via `llvm-as vtable_stubs.ll -o vtable_stubs.bc`.
/// No C compiler needed.
fn generate_llvm_ir_stubs(
    by_class: &std::collections::BTreeMap<String, Vec<&InterfaceMethod>>,
) -> String {
    let mut out = String::new();
    out.push_str("; Auto-generated vtable stubs for SAW verification\n");
    out.push_str("; Load directly: m_stubs <- llvm_load_module \"vtable_stubs.ll\";\n");
    out.push_str("; Or assemble:   llvm-as vtable_stubs.ll -o vtable_stubs.bc\n");
    out.push_str(";\n");
    out.push_str("; SAW resolves indirect vtable calls through these:\n");
    out.push_str(";   this->vptr -> vtable[slot] -> stub function -> havoc spec\n\n");
    out.push_str("target datalayout = \"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n");
    out.push_str("target triple = \"x86_64-pc-windows-msvc\"\n\n");

    for (class_name, class_methods) in by_class {
        let safe_class = sanitize_name(class_name).to_lowercase();

        out.push_str(&format!("; ---- {class_name} vtable ----\n\n"));

        // Destructor stub: takes ptr, returns void
        out.push_str(&format!(
            "define void @{safe_class}_dtor_stub(ptr %self) {{\n  ret void\n}}\n\n"
        ));

        // Method stubs
        for method in class_methods {
            let stub_name = stub_function_name(method);
            let ret_ir = type_to_llvm_ir(&method.method.return_type);
            let params_ir = method_params_to_ir(&method.method);

            out.push_str(&format!(
                "; {class_name}::{} [{}]\n",
                method.method.name,
                if method.is_pure { "pure virtual" } else { "virtual" },
            ));
            out.push_str(&format!(
                "define {ret_ir} @{stub_name}({params_ir}) {{\n"
            ));
            out.push_str(&format!("  {}\n", ir_default_return(&ret_ir)));
            out.push_str("}\n\n");
        }

        // Vtable global: array of function pointers
        let slot_count = class_methods.len() + 1;
        out.push_str(&format!(
            "; Concrete vtable for {class_name}\n"
        ));
        out.push_str(&format!(
            "@{safe_class}_vtable = global [{slot_count} x ptr] [\n"
        ));
        out.push_str(&format!(
            "  ptr @{safe_class}_dtor_stub"
        ));
        for method in class_methods {
            let stub_name = stub_function_name(method);
            out.push_str(&format!(",\n  ptr @{stub_name}"));
        }
        out.push_str("\n]\n\n");
    }

    out
}

/// Convert a TypeInfo to LLVM IR type string.
fn type_to_llvm_ir(ty: &TypeInfo) -> String {
    match ty {
        TypeInfo::Void => "void".into(),
        TypeInfo::Bool => "i1".into(),
        TypeInfo::SignedInt(bits) | TypeInfo::UnsignedInt(bits) => format!("i{bits}"),
        TypeInfo::Pointer(_) => "ptr".into(),
        TypeInfo::Struct { size_bytes: Some(n), .. } => format!("[{n} x i8]"),
        TypeInfo::ByteArray(n) => format!("[{n} x i8]"),
        _ => "ptr".into(), // default to opaque pointer for complex types
    }
}

/// Generate LLVM IR parameter list for a method's stub.
fn method_params_to_ir(func: &FunctionInfo) -> String {
    func.params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let ty = match &p.ty {
                TypeInfo::Pointer(_) => "ptr".to_string(),
                other => type_to_llvm_ir(other),
            };
            format!("{ty} %arg{i}")
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Default return instruction for an LLVM IR type.
fn ir_default_return(ir_type: &str) -> String {
    match ir_type {
        "void" => "ret void".into(),
        "i1" => "ret i1 false".into(),
        t => format!("ret {t} 0"),
    }
}

/// Generate an adversarial havoc SAW spec for one virtual method.
///
/// Models the most adversarial behavior consistent with annotations and types:
///
/// **Annotation semantics** (SAL / prefast / const):
///   - `_In_` / `const T*` / `_In_reads_(n)` → preserved (read-only)
///   - `_Out_` / `_Out_writes_(n)` → havoced (write-only, any final value)
///   - `_Inout_` / `T*` (non-const) → havoced (read-write, any final value)
///   - `const` method → `this` is preserved
///   - non-const method → `this` is havoced (all fields get arbitrary values)
///
/// **Struct field decomposition**:
///   - When a struct type has known fields, each field gets its own fresh var
///   - Pointer fields → nested allocation with the same const/mutable semantics
///   - Uses `llvm_struct_value` for field-level precision instead of opaque blobs
///
/// **NOT modeled** (noted in output, requires manual extension):
///   - Global/static variable writes
///   - Pointer chains deeper than 2 levels
///   - Aliased memory not visible in the type signature
fn generate_havoc_spec(imethod: &InterfaceMethod) -> String {
    let mut out = String::new();
    let func = &imethod.method;
    let stub_name = stub_function_name(imethod);
    let safe_name = sanitize_name(&stub_name);

    out.push_str(&format!(
        "// Adversarial havoc spec for {}::{}\n",
        imethod.class_name, func.name,
    ));
    out.push_str("//\n");
    out.push_str("// Models ANY implementation consistent with type-system and SAL constraints.\n");
    out.push_str("// The solver can choose ANY value for mutable/writable memory after the call.\n");
    out.push_str("// Const/_In_ memory is preserved — the solver cannot modify it.\n");
    out.push_str("//\n");
    out.push_str("// Annotation key:\n");
    out.push_str("//   _In_ / const    → PRESERVED (read-only, unchanged after call)\n");
    out.push_str("//   _Out_           → HAVOCED   (write-only, any final value)\n");
    out.push_str("//   _Inout_ / &mut  → HAVOCED   (read-write, any final value)\n");
    out.push_str("//   no annotation   → inferred from const/mutable\n");
    out.push_str("//\n");
    out.push_str("// NOT modeled: global writes, pointer chains >2 deep, aliased memory.\n\n");

    out.push_str(&format!(
        "let {safe_name}_havoc : LLVMSetup () = do {{\n"
    ));

    let mut setup = String::new();
    let mut postconds = String::new();
    let mut args = Vec::new();

    for param in &func.params {
        let is_indirect = matches!(&param.ty, TypeInfo::Pointer(_));
        if !is_indirect {
            let saw_type = type_to_saw(&param.ty);
            setup.push_str(&format!(
                "\n    // Parameter: {} (pass-by-value)\n",
                param.name,
            ));
            setup.push_str(&format!(
                "    {} <- llvm_fresh_var \"{}\" ({});\n",
                param.name, param.name, saw_type,
            ));
            args.push(format!("llvm_term {}", param.name));
            continue;
        }

        let inner_ty = match &param.ty {
            TypeInfo::Pointer(inner) => inner.as_ref(),
            _ => unreachable!(),
        };

        // Determine havoc behavior from annotations + type system
        let behavior = resolve_param_behavior(param);

        emit_adversarial_param(
            &param.name,
            inner_ty,
            behavior,
            &param.annotations,
            &mut setup,
            &mut postconds,
        );
        args.push(format!("{}_ptr", param.name));
    }

    out.push_str(&setup);

    // Execute
    out.push_str(&format!(
        "\n    llvm_execute_func [{}];\n",
        args.join(", "),
    ));

    // Return value
    let ret_saw = type_to_saw(&func.return_type);
    if ret_saw != "// void" {
        out.push_str("\n    // Return: unconstrained (solver chooses any value)\n");
        out.push_str(&format!(
            "    ret <- llvm_fresh_var \"ret\" ({ret_saw});\n"
        ));
        out.push_str("    llvm_return (llvm_term ret);\n");
    }

    // Postconditions
    if !postconds.is_empty() {
        out.push_str("\n    // --- Postconditions ---\n");
        out.push_str(&postconds);
    }

    out.push_str("};\n");
    out
}

/// Whether a parameter's memory is preserved or havoced.
#[derive(Debug, Clone, Copy, PartialEq)]
enum HavocBehavior {
    /// Memory preserved after call (const / _In_)
    Preserved,
    /// Memory havoced: solver picks any final value (_Out_ / _Inout_ / mutable)
    Havoced,
}

/// Resolve parameter behavior from SAL annotations + type system.
///
/// Resolve parameter behavior: **strictest constraint wins.**
///
/// Sources (any saying "preserved" forces preserved):
///   - Type system: `const T*` / `const T&` → preserved
///   - SAL `_In_` / `_In_reads_` → preserved
///   - SAL `_Out_` / `_Out_writes_` → havoced (unless const overrides)
///   - SAL `_Inout_` → havoced (unless const overrides)
///   - non-const with no annotation → havoced
///
/// If ANY source says "preserved", the result is preserved.
fn resolve_param_behavior(param: &ParamInfo) -> HavocBehavior {
    let type_says_const = param.mutability == Mutability::Readonly;
    let sal_says_readonly = param.annotations.iter().any(|a| matches!(a, Annotation::InReads(_)));

    // If either the type system or SAL says readonly, it's preserved
    if type_says_const || sal_says_readonly {
        return HavocBehavior::Preserved;
    }

    // Otherwise check if SAL explicitly says writable
    let sal_says_writable = param.annotations.iter().any(|a| {
        matches!(a, Annotation::OutWrites(_) | Annotation::Inout)
    });
    if sal_says_writable {
        return HavocBehavior::Havoced;
    }

    // No annotations — fall back to type system
    match param.mutability {
        Mutability::Readonly => HavocBehavior::Preserved,
        Mutability::Mutable | Mutability::WriteOnly => HavocBehavior::Havoced,
    }
}

/// Emit setup + postconditions for a pointer parameter using the adversarial model.
///
/// For structs with known fields: decomposes into per-field fresh vars.
/// For structs with only a size: uses opaque byte array.
/// For nested pointers in struct fields: allocates and havocs/preserves targets.
fn emit_adversarial_param(
    name: &str,
    inner_ty: &TypeInfo,
    behavior: HavocBehavior,
    annotations: &[Annotation],
    setup: &mut String,
    postconds: &mut String,
) {
    let is_preserved = behavior == HavocBehavior::Preserved;
    let alloc_kind = if is_preserved { "llvm_alloc_readonly" } else { "llvm_alloc" };

    // Determine annotation label for comments
    let ann_label = annotation_label(annotations, is_preserved);

    // Check for sized buffer annotations: _In_reads_(n) or _Out_writes_(n)
    let buffer_size = annotations.iter().find_map(|a| match a {
        Annotation::InReads(n) if *n > 0 => Some(*n),
        Annotation::OutWrites(n) if *n > 0 => Some(*n),
        _ => None,
    });

    if let Some(n) = buffer_size {
        // SAL-annotated buffer: allocate array of exact size
        let elem_saw = match inner_ty {
            TypeInfo::Pointer(elem) => type_to_saw(elem),
            _ => type_to_saw(inner_ty),
        };
        let buf_type = format!("llvm_array {n} ({elem_saw})");

        setup.push_str(&format!("\n    // Parameter: {name} ({ann_label}, buffer[{n}])\n"));
        setup.push_str(&format!("    {name}_ptr <- {alloc_kind} ({buf_type});\n"));
        setup.push_str(&format!(
            "    {name}_val <- llvm_fresh_var \"{name}\" ({buf_type});\n"
        ));
        setup.push_str(&format!("    llvm_points_to {name}_ptr (llvm_term {name}_val);\n"));

        if is_preserved {
            postconds.push_str(&format!("    // {name}: _In_reads_({n}) → buffer preserved\n"));
            postconds.push_str(&format!(
                "    llvm_points_to {name}_ptr (llvm_term {name}_val);\n"
            ));
        } else {
            postconds.push_str(&format!(
                "    // {name}: _Out_writes_({n}) → buffer HAVOCED (any {n} elements)\n"
            ));
            postconds.push_str(&format!(
                "    {name}_after <- llvm_fresh_var \"{name}_after\" ({buf_type});\n"
            ));
            postconds.push_str(&format!(
                "    llvm_points_to {name}_ptr (llvm_term {name}_after);\n"
            ));
        }
        return;
    }

    // Struct with known fields → decompose per-field
    if let TypeInfo::Struct {
        name: struct_name,
        fields,
        ..
    } = inner_ty
    {
        if !fields.is_empty() {
            emit_struct_decomposed(
                name,
                struct_name,
                fields,
                is_preserved,
                alloc_kind,
                &ann_label,
                setup,
                postconds,
            );
            return;
        }
    }

    // Default: opaque type (no field info)
    let saw_type = type_to_saw(inner_ty);
    setup.push_str(&format!("\n    // Parameter: {name} ({ann_label})\n"));
    setup.push_str(&format!("    {name}_ptr <- {alloc_kind} ({saw_type});\n"));
    setup.push_str(&format!(
        "    {name}_val <- llvm_fresh_var \"{name}\" ({saw_type});\n"
    ));
    setup.push_str(&format!("    llvm_points_to {name}_ptr (llvm_term {name}_val);\n"));

    if is_preserved {
        postconds.push_str(&format!("    // {name}: {ann_label} → memory unchanged\n"));
        postconds.push_str(&format!(
            "    llvm_points_to {name}_ptr (llvm_term {name}_val);\n"
        ));
    } else {
        postconds.push_str(&format!(
            "    // {name}: {ann_label} → solver chooses ANY final value\n"
        ));
        postconds.push_str(&format!(
            "    {name}_after <- llvm_fresh_var \"{name}_after\" ({saw_type});\n"
        ));
        postconds.push_str(&format!(
            "    llvm_points_to {name}_ptr (llvm_term {name}_after);\n"
        ));
    }
}

/// Emit struct with per-field decomposition.
fn emit_struct_decomposed(
    param_name: &str,
    struct_name: &str,
    fields: &[(String, TypeInfo)],
    is_preserved: bool,
    alloc_kind: &str,
    ann_label: &str,
    setup: &mut String,
    postconds: &mut String,
) {
    let saw_type = type_to_saw(&TypeInfo::Struct {
        name: struct_name.to_string(),
        size_bytes: None,
        fields: fields.to_vec(),
    });

    setup.push_str(&format!(
        "\n    // Parameter: {param_name} → {struct_name} ({ann_label})\n"
    ));
    setup.push_str(&format!("    {param_name}_ptr <- {alloc_kind} ({saw_type});\n"));

    // Pre-state: allocate fresh var per scalar field, alloc per pointer field
    let mut pre_field_terms = Vec::new();
    let mut nested_ptrs: Vec<(String, String, bool)> = Vec::new(); // (name, saw_type, is_ptr)

    for (field_name, field_ty) in fields {
        let var_name = format!("{param_name}_{field_name}");
        match field_ty {
            TypeInfo::Pointer(pointee) => {
                let pointee_saw = type_to_saw(pointee);
                let nested_alloc = if is_preserved { "llvm_alloc_readonly" } else { "llvm_alloc" };
                setup.push_str(&format!(
                    "    {var_name}_ptr <- {nested_alloc} ({pointee_saw});\n"
                ));
                setup.push_str(&format!(
                    "    {var_name}_val <- llvm_fresh_var \"{var_name}\" ({pointee_saw});\n"
                ));
                setup.push_str(&format!(
                    "    llvm_points_to {var_name}_ptr (llvm_term {var_name}_val);\n"
                ));
                pre_field_terms.push(format!("{var_name}_ptr"));
                nested_ptrs.push((var_name, pointee_saw, true));
            }
            _ => {
                let field_saw = type_to_saw(field_ty);
                setup.push_str(&format!(
                    "    {var_name} <- llvm_fresh_var \"{var_name}\" ({field_saw});\n"
                ));
                pre_field_terms.push(format!("llvm_term {var_name}"));
                nested_ptrs.push((var_name, field_saw, false));
            }
        }
    }

    // Wire struct pre-state
    setup.push_str(&format!(
        "    llvm_points_to {param_name}_ptr (llvm_struct_value\n        [ {} ]);\n",
        pre_field_terms.join("\n        , "),
    ));

    // Post-state
    if is_preserved {
        // All fields preserved
        postconds.push_str(&format!(
            "    // {param_name} ({struct_name}): {ann_label} → all fields preserved\n"
        ));
        let mut post_terms = Vec::new();
        for (var_name, _, is_ptr) in &nested_ptrs {
            if *is_ptr {
                postconds.push_str(&format!(
                    "    llvm_points_to {var_name}_ptr (llvm_term {var_name}_val);\n"
                ));
                post_terms.push(format!("{var_name}_ptr"));
            } else {
                post_terms.push(format!("llvm_term {var_name}"));
            }
        }
        postconds.push_str(&format!(
            "    llvm_points_to {param_name}_ptr (llvm_struct_value\n        [ {} ]);\n",
            post_terms.join("\n        , "),
        ));
    } else {
        // All fields havoced
        postconds.push_str(&format!(
            "    // {param_name} ({struct_name}): {ann_label} → ALL fields HAVOCED\n"
        ));
        let mut post_terms = Vec::new();
        for (var_name, saw_type, is_ptr) in &nested_ptrs {
            if *is_ptr {
                postconds.push_str(&format!(
                    "    // {var_name}: pointer target → HAVOCED\n"
                ));
                postconds.push_str(&format!(
                    "    {var_name}_after <- llvm_fresh_var \"{var_name}_after\" ({saw_type});\n"
                ));
                postconds.push_str(&format!(
                    "    llvm_points_to {var_name}_ptr (llvm_term {var_name}_after);\n"
                ));
                // The pointer value in the struct itself is also havoced
                let ptr_after = format!("{var_name}_ptr_after");
                postconds.push_str(&format!(
                    "    {ptr_after} <- llvm_alloc ({saw_type});\n"
                ));
                post_terms.push(ptr_after);
            } else {
                postconds.push_str(&format!(
                    "    {var_name}_after <- llvm_fresh_var \"{var_name}_after\" ({saw_type});\n"
                ));
                post_terms.push(format!("llvm_term {var_name}_after"));
            }
        }
        postconds.push_str(&format!(
            "    llvm_points_to {param_name}_ptr (llvm_struct_value\n        [ {} ]);\n",
            post_terms.join("\n        , "),
        ));
    }
}

/// Generate a human-readable label for the annotation-derived behavior.
fn annotation_label(annotations: &[Annotation], is_preserved: bool) -> String {
    for ann in annotations {
        match ann {
            Annotation::InReads(0) => return "_In_ → preserved".into(),
            Annotation::InReads(n) => return format!("_In_reads_({n}) → preserved"),
            Annotation::OutWrites(0) => return "_Out_ → HAVOCED".into(),
            Annotation::OutWrites(n) => return format!("_Out_writes_({n}) → HAVOCED"),
            Annotation::Inout => return "_Inout_ → HAVOCED".into(),
            _ => {}
        }
    }
    if is_preserved {
        "const → preserved".into()
    } else {
        "mutable → HAVOCED".into()
    }
}

/// Generate the index file with vtable-aware override setup.
///
/// Produces:
/// - Includes for all havoc spec files
/// - llvm_unsafe_assume_spec for each stub
/// - Per-class helper: `alloc_<class>_this` that allocates a `this` pointer
///   whose first 8 bytes (vptr) point to the concrete vtable global
fn generate_override_index_with_vtable(
    methods: &[InterfaceMethod],
    by_class: &std::collections::BTreeMap<String, Vec<&InterfaceMethod>>,
) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated interface override setup with vtable resolution\n");
    out.push_str("//\n");
    out.push_str("// For DIRECT calls (function is 'declare' in bitcode):\n");
    out.push_str("//   Just use llvm_unsafe_assume_spec with the mangled name directly.\n");
    out.push_str("//   No extra files needed — the havoc specs bind to the declared symbol.\n");
    out.push_str("//\n");
    out.push_str("// For VTABLE INDIRECT calls (virtual dispatch through this->vptr):\n");
    out.push_str("//   m_stubs <- llvm_load_module \"vtable_stubs.ll\";\n");
    out.push_str("//   m       <- llvm_combine_modules m_main m_stubs;\n");
    out.push_str("//   The vtable global provides the function pointer resolution chain:\n");
    out.push_str("//     this->vptr -> vtable[slot] -> stub function -> havoc spec\n");
    out.push_str("//\n");
    out.push_str("// Usage:\n");
    out.push_str("//   m_main  <- llvm_load_module \"your_code.bc\";\n");
    out.push_str("//   m_stubs <- llvm_load_module \"vtable_stubs.ll\";\n");
    out.push_str("//   m       <- llvm_combine_modules m_main m_stubs;\n");
    out.push_str("//   include \"interface_overrides.saw\";\n");
    out.push_str("//\n");
    out.push_str("// For each interface class, a helper is generated:\n");
    out.push_str("//   alloc_<class>_this : LLVMSetup Term\n");
    out.push_str("// which allocates a properly-formed `this` pointer with vptr wired\n");
    out.push_str("// to the stub vtable. Use it in your verification specs.\n\n");

    // Include each havoc spec file
    for method in methods {
        let filename = format!(
            "{}_{}_havoc_spec.saw",
            sanitize_name(&method.class_name),
            sanitize_name(&method.method.name),
        );
        out.push_str(&format!("include \"{filename}\";\n"));
    }
    out.push('\n');

    // Emit llvm_unsafe_assume_spec for each method
    let mut all_overrides = Vec::new();

    out.push_str("// --- Override bindings ---\n");
    out.push_str("// For vtable dispatch: binds to stub function names (from vtable_stubs.ll)\n");
    out.push_str("// For direct calls: binds to the mangled C++ name (already in your bitcode)\n\n");

    for method in methods {
        let stub_name = stub_function_name(method);
        let safe_name = sanitize_name(&stub_name);
        let mangled = method
            .method
            .mangled_name
            .as_deref();

        out.push_str(&format!(
            "// {}::{} — havoc: any behavior consistent with type constraints\n",
            method.class_name, method.method.name,
        ));

        // Vtable stub binding (for indirect calls via vtable_stubs.ll)
        out.push_str(&format!(
            "ov_{safe_name} <- llvm_unsafe_assume_spec m \"{stub_name}\" {safe_name}_havoc;\n",
        ));
        all_overrides.push(format!("ov_{safe_name}"));

        // Mangled name binding (for direct calls — no stubs needed)
        if let Some(mangled_name) = mangled {
            let safe_mangled = sanitize_name(mangled_name);
            out.push_str(&format!(
                "ov_{safe_mangled} <- llvm_unsafe_assume_spec m \"{mangled_name}\" {safe_name}_havoc;\n",
            ));
            all_overrides.push(format!("ov_{safe_mangled}"));
        }
        out.push('\n');
    }

    // Emit per-class vtable setup helpers
    for (class_name, class_methods) in by_class {
        let safe_class = sanitize_name(class_name).to_lowercase();

        out.push_str(&format!(
            "// ===========================================================\n"
        ));
        out.push_str(&format!(
            "// {class_name}: vtable setup helper\n"
        ));
        out.push_str(&format!(
            "// ===========================================================\n"
        ));
        out.push_str(&format!(
            "//\n"
        ));
        out.push_str(&format!(
            "// Allocates a `this` pointer (8 bytes for vptr) with the vtable\n"
        ));
        out.push_str(&format!(
            "// pointer wired to {safe_class}_vtable. SAW resolves:\n"
        ));
        out.push_str(&format!(
            "//   this -> vptr -> {safe_class}_vtable[slot] -> stub -> havoc spec\n"
        ));
        out.push_str(&format!(
            "//\n"
        ));
        out.push_str(&format!(
            "// Use in your spec like:\n"
        ));
        out.push_str(&format!(
            "//   this_ptr <- alloc_{safe_class}_this;\n"
        ));

        // Collect override names for this class
        let class_ov_names: Vec<String> = class_methods
            .iter()
            .map(|m| format!("ov_{}", sanitize_name(&stub_function_name(m))))
            .collect();
        if !class_ov_names.is_empty() {
            out.push_str(&format!(
                "//   llvm_verify m \"target\" [{}] false spec z3;\n",
                class_ov_names.join(", "),
            ));
        }
        out.push('\n');

        let slot_count = class_methods.len() + 1; // +1 for dtor

        out.push_str(&format!(
            "let alloc_{safe_class}_this : LLVMSetup (Term, Term) = do {{\n"
        ));
        out.push_str(&format!(
            "    // Allocate the vtable: {slot_count} function pointers\n"
        ));
        out.push_str(&format!(
            "    let vtable_ty = llvm_array {slot_count} (llvm_int 64);\n"
        ));
        out.push_str(&format!(
            "    vtable_ptr <- llvm_alloc_readonly_aligned 8 vtable_ty;\n"
        ));
        out.push_str(&format!(
            "\n    // Point vtable slots to the global stub vtable\n"
        ));
        out.push_str(&format!(
            "    llvm_points_to_at_type vtable_ptr vtable_ty\n"
        ));
        out.push_str(&format!(
            "        (llvm_global_initializer \"{safe_class}_vtable\");\n"
        ));
        out.push_str(&format!(
            "\n    // Allocate `this`: first 8 bytes = vptr -> vtable\n"
        ));
        out.push_str(&format!(
            "    this_ptr <- llvm_alloc (llvm_array 8 (llvm_int 8));\n"
        ));
        out.push_str(&format!(
            "    llvm_points_to this_ptr vtable_ptr;\n"
        ));
        out.push_str(&format!(
            "\n    return (this_ptr, vtable_ptr);\n"
        ));
        out.push_str("};\n\n");
    }

    // Emit convenience: list of all override names
    out.push_str("// All overrides for use in llvm_verify:\n");
    out.push_str(&format!(
        "// let all_interface_overrides = [{}];\n",
        all_overrides.join(", "),
    ));

    out
}

/// Generate the extern "C" stub function name.
fn stub_function_name(method: &InterfaceMethod) -> String {
    format!(
        "{}_{}_stub",
        sanitize_name(&method.class_name).to_lowercase(),
        sanitize_name(&method.method.name).to_lowercase(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_spec(
        name: &str,
        params: Vec<ParamConstraint>,
        return_type: &str,
        can_throw: bool,
    ) -> SpecConstraint {
        SpecConstraint {
            function_name: name.into(),
            mangled_name: None,
            params,
            return_constraint: ReturnConstraint {
                saw_type: return_type.into(),
                value_constraints: vec![],
            },
            can_throw,
            postconditions: vec![],
        }
    }

    #[test]
    fn test_generate_llvm_spec_readonly() {
        let spec = make_spec(
            "test_fn",
            vec![ParamConstraint {
                name: "x".into(),
                alloc_type: AllocType::AllocReadonly,
                saw_type: "llvm_int 32".into(),
                preconditions: vec![],
                unchanged_after: true,
            }],
            "// void",
            false,
        );
        let output = generate_saw_spec(&spec);
        assert!(output.contains("LLVMSetup ()"));
        assert!(output.contains("llvm_alloc_readonly"));
        assert!(output.contains("llvm_fresh_var"));
        assert!(output.contains("llvm_execute_func"));
    }

    #[test]
    fn test_generate_llvm_spec_mutable() {
        let spec = make_spec(
            "mutate_fn",
            vec![ParamConstraint {
                name: "buf".into(),
                alloc_type: AllocType::AllocMutable,
                saw_type: "llvm_int 64".into(),
                preconditions: vec![],
                unchanged_after: false,
            }],
            "// void",
            false,
        );
        let output = generate_saw_spec(&spec);
        assert!(output.contains("llvm_alloc (llvm_int 64)"));
        assert!(!output.contains("llvm_alloc_readonly"));
    }

    #[test]
    fn test_generate_llvm_spec_freshvar() {
        let spec = make_spec(
            "add",
            vec![
                ParamConstraint {
                    name: "a".into(),
                    alloc_type: AllocType::FreshVar,
                    saw_type: "llvm_int 32".into(),
                    preconditions: vec![],
                    unchanged_after: false,
                },
                ParamConstraint {
                    name: "b".into(),
                    alloc_type: AllocType::FreshVar,
                    saw_type: "llvm_int 32".into(),
                    preconditions: vec![],
                    unchanged_after: false,
                },
            ],
            "llvm_int 32",
            false,
        );
        let output = generate_saw_spec(&spec);
        assert!(output.contains("a <- llvm_fresh_var \"a\" (llvm_int 32)"));
        assert!(output.contains("llvm_term a, llvm_term b"));
    }

    #[test]
    fn test_generate_llvm_spec_return() {
        let spec = make_spec(
            "get_val",
            vec![],
            "llvm_int 32",
            false,
        );
        let output = generate_saw_spec(&spec);
        assert!(output.contains("ret <- llvm_fresh_var \"ret\" (llvm_int 32)"));
        assert!(output.contains("llvm_return (llvm_term ret)"));
    }

    #[test]
    fn test_generate_llvm_spec_void_return() {
        let spec = make_spec("noop", vec![], "// void", false);
        let output = generate_saw_spec(&spec);
        assert!(!output.contains("llvm_return"));
    }

    #[test]
    fn test_generate_llvm_spec_can_throw() {
        let spec = make_spec("risky", vec![], "// void", true);
        let output = generate_saw_spec(&spec);
        assert!(output.contains("WARNING: Function may throw"));
    }

    #[test]
    fn test_generate_mir_spec_basic() {
        let spec = make_spec(
            "rust_fn",
            vec![ParamConstraint {
                name: "x".into(),
                alloc_type: AllocType::FreshVar,
                saw_type: "llvm_int 32".into(),
                preconditions: vec![],
                unchanged_after: false,
            }],
            "llvm_int 32",
            false,
        );
        let output = generate_mir_spec(&spec);
        assert!(output.contains("MIRSetup ()"));
        assert!(output.contains("mir_fresh_var"));
        assert!(output.contains("mir_execute_func"));
        assert!(output.contains("mir_return"));
    }

    #[test]
    fn test_generate_mir_spec_alloc() {
        let spec = make_spec(
            "rust_ref_fn",
            vec![ParamConstraint {
                name: "data".into(),
                alloc_type: AllocType::AllocReadonly,
                saw_type: "llvm_int 64".into(),
                preconditions: vec![],
                unchanged_after: true,
            }],
            "// void",
            false,
        );
        let output = generate_mir_spec(&spec);
        assert!(output.contains("mir_alloc_readonly"));
        assert!(output.contains("mir_points_to"));
    }

    #[test]
    fn test_sanitize_name() {
        assert_eq!(sanitize_name("simple"), "simple");
        assert_eq!(sanitize_name("my::func"), "my__func");
        assert_eq!(sanitize_name("ns::Class<int>"), "ns__Class_int_");
    }

    #[test]
    fn test_mir_saw_type_mapping() {
        assert_eq!(mir_saw_type("llvm_int 32"), "mir_u32");
        assert_eq!(mir_saw_type("llvm_int 8"), "mir_u8");
        assert_eq!(
            mir_saw_type("llvm_alias \"MyStruct\""),
            "mir_find_adt m \"MyStruct\""
        );
    }

    #[test]
    fn test_emit_saw_specs_creates_files() {
        let dir = std::env::temp_dir().join("saw_spec_gen_test_emit");
        let _ = fs::remove_dir_all(&dir);

        let specs = vec![make_spec("test_fn", vec![], "// void", false)];
        emit_saw_specs(&specs, &dir).unwrap();

        assert!(dir.join("test_fn_auto_spec.saw").exists());
        assert!(dir.join("auto_specs.saw").exists());

        let index = fs::read_to_string(dir.join("auto_specs.saw")).unwrap();
        assert!(index.contains("include \"test_fn_auto_spec.saw\""));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_emit_mir_saw_specs() {
        let dir = std::env::temp_dir().join("saw_spec_gen_test_mir_emit");
        let _ = fs::remove_dir_all(&dir);

        let specs = vec![make_spec("rust_fn", vec![], "llvm_int 32", false)];
        emit_mir_saw_specs(&specs, &dir).unwrap();

        let content =
            fs::read_to_string(dir.join("rust_fn_auto_spec.saw")).unwrap();
        assert!(content.contains("MIRSetup"));

        let index = fs::read_to_string(dir.join("auto_specs.saw")).unwrap();
        assert!(index.contains("Mode: MIR"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_generate_postconditions() {
        let spec = SpecConstraint {
            function_name: "read_fn".into(),
            mangled_name: None,
            params: vec![ParamConstraint {
                name: "data".into(),
                alloc_type: AllocType::AllocReadonly,
                saw_type: "llvm_int 32".into(),
                preconditions: vec![],
                unchanged_after: true,
            }],
            return_constraint: ReturnConstraint {
                saw_type: "// void".into(),
                value_constraints: vec![],
            },
            can_throw: false,
            postconditions: vec![
                "llvm_points_to data_ptr (llvm_term data_before)".into(),
            ],
        };
        let output = generate_saw_spec(&spec);
        assert!(output.contains("Postconditions"));
        assert!(output.contains("data_before"));
    }
}
