//! Emit SAW verification scripts from derived constraints.
//!
//! Generates .saw files that can be loaded by SAW to create override
//! specs for unspecified functions.

use crate::constraints::*;
use anyhow::{Context, Result};
use std::fs;
use std::io::Write;
use std::path::Path;

/// Emit SAW spec files for all constraints.
pub fn emit_saw_specs(specs: &[SpecConstraint], output_dir: &Path) -> Result<()> {
    fs::create_dir_all(output_dir)
        .with_context(|| format!("Failed to create output directory {}", output_dir.display()))?;

    for spec in specs {
        let filename = format!("{}_auto_spec.saw", sanitize_name(&spec.function_name));
        let filepath = output_dir.join(&filename);
        let mut file = fs::File::create(&filepath)
            .with_context(|| format!("Failed to create {}", filepath.display()))?;

        write!(file, "{}", generate_saw_spec(spec))?;
    }

    // Also generate an index file that includes all specs
    let index_path = output_dir.join("auto_specs.saw");
    let mut index = fs::File::create(&index_path)?;
    writeln!(index, "// Auto-generated SAW specs — do not edit")?;
    writeln!(
        index,
        "// Generated by saw-spec-gen from type system constraints"
    )?;
    writeln!(index)?;
    for spec in specs {
        let filename = format!("{}_auto_spec.saw", sanitize_name(&spec.function_name));
        writeln!(index, "include \"{filename}\";")?;
    }

    Ok(())
}

fn generate_saw_spec(spec: &SpecConstraint) -> String {
    let mut out = String::new();
    let fn_name = &spec.function_name;
    let target_name = spec
        .mangled_name
        .as_deref()
        .unwrap_or(&spec.function_name);

    out.push_str(&format!(
        "// Auto-generated spec for: {fn_name}\n"
    ));
    out.push_str(&format!(
        "// Constraints derived from type system and annotations\n"
    ));
    if spec.can_throw {
        out.push_str("// WARNING: Function may throw — exception path not modeled\n");
    }
    out.push_str(&format!(
        "\nlet {safe_name}_auto_spec : LLVMSetup () = do {{\n",
        safe_name = sanitize_name(fn_name),
    ));

    // Emit parameter setup
    for param in &spec.params {
        out.push_str(&format!("\n    // Parameter: {}\n", param.name));

        match param.alloc_type {
            AllocType::AllocReadonly => {
                out.push_str(&format!(
                    "    {name}_ptr <- llvm_alloc_readonly ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    {name}_before <- llvm_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    llvm_points_to {name}_ptr (llvm_term {name}_before);\n",
                    name = param.name,
                ));
            }
            AllocType::AllocMutable => {
                out.push_str(&format!(
                    "    {name}_ptr <- llvm_alloc ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    {name}_val <- llvm_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
                out.push_str(&format!(
                    "    llvm_points_to {name}_ptr (llvm_term {name}_val);\n",
                    name = param.name,
                ));
            }
            AllocType::FreshVar => {
                out.push_str(&format!(
                    "    {name} <- llvm_fresh_var \"{name}\" ({ty});\n",
                    name = param.name,
                    ty = param.saw_type,
                ));
            }
        }

        for pre in &param.preconditions {
            out.push_str(&format!("    {pre};\n"));
        }
    }

    // Emit execute_func
    let args: Vec<String> = spec
        .params
        .iter()
        .map(|p| match p.alloc_type {
            AllocType::AllocReadonly | AllocType::AllocMutable => format!("{}_ptr", p.name),
            AllocType::FreshVar => format!("llvm_term {}", p.name),
        })
        .collect();
    out.push_str(&format!(
        "\n    llvm_execute_func [{}];\n",
        args.join(", ")
    ));

    // Emit return value
    if spec.return_constraint.saw_type != "// void" {
        out.push_str(&format!(
            "\n    ret <- llvm_fresh_var \"ret\" ({});\n",
            spec.return_constraint.saw_type,
        ));
        for vc in &spec.return_constraint.value_constraints {
            out.push_str(&format!("    {vc};\n"));
        }
        out.push_str("    llvm_return (llvm_term ret);\n");
    }

    // Emit postconditions (readonly params unchanged)
    if !spec.postconditions.is_empty() {
        out.push_str("\n    // Postconditions: readonly params unchanged\n");
        for post in &spec.postconditions {
            out.push_str(&format!("    {post};\n"));
        }
    }

    out.push_str("};");

    // Add the assume_spec call
    out.push_str(&format!(
        "\n\n// Usage: ov_{safe} <- llvm_unsafe_assume_spec m \"{target}\" {safe}_auto_spec;\n",
        safe = sanitize_name(fn_name),
        target = target_name,
    ));

    out
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
