//! `std::vector` functional SAW spec emission. See sibling
//! [`super::bitcode_overrides_functional`] for the dispatcher and
//! the per-container architecture.
//!
//! ## Approach: SAW ghost state couples push_back ↔ back
//!
//! Modeling the full `_M_start / _M_finish / _M_end_of_storage`
//! triple plus the heap buffer is enormous. For the canonical
//! "push then read back" pattern in
//! `tests/e2e/cases/10-stl-coverage/vector_back_havoc/`, a much
//! cheaper coupling suffices: a single SAW ghost variable holds the
//! most-recently-pushed value, and `back()` returns a fresh symbolic
//! allocation that the ghost constrains to equal the pushed value.
//!
//! The ghost variable is declared **once** at the top of the
//! overrides snippet via [`emit_vector_ghost_decl`]; the dispatcher
//! in [`super::bitcode_overrides::emit_overrides`] pre-scans the
//! target list and emits the declaration only when at least one
//! recognized vector method is present, so non-vector verifications
//! pay no overhead.
//!
//! ## Method coverage
//!
//! Currently models the default ctor, dtor, `push_back(T&&)`, and
//! `back()`. This is exactly the call set generated by `v.push_back(
//! x + 1u); return v.back();` on libstdc++, which is the regression
//! target.

use super::bitcode_overrides_functional::StlMethod;

/// Name of the shared ghost variable. One per script — the model
/// assumes a single live vector (sufficient for the regression
/// target; multi-vector programs would need per-pointer ghost state).
pub const VECTOR_GHOST_NAME: &str = "vec_back_val_ghost";

/// Bit-width of the modeled element type. Right now we only recognize
/// `uint32_t` / `int32_t` vectors (`Ij` / `Ii` in Itanium mangling).
/// Returns `None` when the mangled name isn't one of the supported
/// instantiations; the caller falls back to the default havoc emitter.
pub fn element_bits_from_mangled(mangled: &str) -> Option<u32> {
    // Itanium pattern: `St6vectorI<elem>SaI<elem>EE`. We look for the
    // first capital `I` after `St6vector` and read the next single
    // character as the primitive code.
    let after_vector = mangled.split("St6vector").nth(1)?;
    let inner = after_vector.strip_prefix('I')?;
    let code = inner.chars().next()?;
    match code {
        'j' | 'i' | 'f' => Some(32),
        'm' | 'l' | 'd' => Some(64),
        'h' | 'a' | 'c' => Some(8),
        't' | 's' => Some(16),
        _ => None,
    }
}

/// Emit the script-level `declare_ghost_state` binding. Must be
/// called **once** per script, before any individual vector override
/// spec. The dispatcher in `bitcode_overrides::emit_overrides`
/// guarantees that ordering.
pub fn emit_vector_ghost_decl(out: &mut String) {
    out.push_str(&format!(
        "\n// Ghost state for std::vector functional overrides: holds\n\
         // the most-recently-pushed element value so back() can return\n\
         // a pointer whose pointee equals it. See\n\
         // src/emit/saw_emit/bitcode_overrides_functional_vector.rs.\n\
         {} <- declare_ghost_state \"{}\";\n",
        VECTOR_GHOST_NAME, VECTOR_GHOST_NAME,
    ));
}

/// Emit a SAW spec block + `llvm_unsafe_assume_spec` binding for one
/// recognized std::vector method. `element_bits` is the width of `T`
/// (e.g. 32 for `std::vector<uint32_t>`).
pub fn emit_vector_override(
    out: &mut String,
    method: StlMethod,
    element_bits: u32,
    symbol: &str,
    safe: &str,
    ov_name: &str,
) {
    out.push_str(&format!(
        "\n// override: {sym}  [stl-functional: {kind:?}]\n",
        sym = symbol,
        kind = method,
    ));
    out.push_str(&format!("let {safe}_spec = do {{\n"));
    out.push_str("    v <- llvm_fresh_pointer (llvm_alias \"class.std::vector\");\n");
    let ghost = VECTOR_GHOST_NAME;
    match method {
        StlMethod::VectorCtorDefault => {
            // Initialise the ghost to a fresh symbolic so that any
            // subsequent `back()` before a `push_back()` is symbolic
            // (rather than reading undefined ghost state, which SAW
            // would reject).
            out.push_str("    llvm_execute_func [v];\n");
            out.push_str(&format!(
                "    init_val <- llvm_fresh_var \"init_val\" (llvm_int {element_bits});\n",
            ));
            out.push_str(&format!("    llvm_ghost_value {ghost} init_val;\n"));
        }
        StlMethod::VectorDtor => {
            // No observable side-effect — leave the post-state empty.
            out.push_str("    llvm_execute_func [v];\n");
        }
        StlMethod::VectorPushBackRvalue => {
            // Argument is `T&&` → IR `ptr` pointing to a T-sized cell.
            out.push_str(&format!("    p <- llvm_alloc (llvm_int {element_bits});\n",));
            out.push_str(&format!(
                "    val <- llvm_fresh_var \"val\" (llvm_int {element_bits});\n",
            ));
            out.push_str("    llvm_points_to p (llvm_term val);\n");
            out.push_str("    llvm_execute_func [v, p];\n");
            out.push_str(&format!("    llvm_ghost_value {ghost} val;\n"));
        }
        StlMethod::VectorBack => {
            // Pre-state: the ghost holds some symbolic value.
            // Post-state: return a fresh allocation whose pointee
            // equals that value. The caller's `load i32, ptr` after
            // the call will pick up the symbolic.
            out.push_str(&format!(
                "    val <- llvm_fresh_var \"back_val\" (llvm_int {element_bits});\n",
            ));
            out.push_str(&format!("    llvm_ghost_value {ghost} val;\n"));
            out.push_str("    llvm_execute_func [v];\n");
            out.push_str(&format!(
                "    out <- llvm_alloc (llvm_int {element_bits});\n",
            ));
            out.push_str("    llvm_points_to out (llvm_term val);\n");
            out.push_str("    llvm_return out;\n");
        }
        _ => unreachable!("emit_vector_override called with non-vector method"),
    }
    out.push_str("};\n");
    out.push_str(&format!(
        "{ov_name} <- llvm_unsafe_assume_spec m \"{symbol}\" {safe}_spec;\n",
    ));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn element_bits_recognizes_uint32() {
        let m = "_ZNSt6vectorIjSaIjEE9push_backEOj";
        assert_eq!(element_bits_from_mangled(m), Some(32));
    }

    #[test]
    fn element_bits_recognizes_uint64() {
        let m = "_ZNSt6vectorImSaImEE9push_backEOm";
        assert_eq!(element_bits_from_mangled(m), Some(64));
    }

    #[test]
    fn element_bits_recognizes_int32() {
        let m = "_ZNSt6vectorIiSaIiEE4backEv";
        assert_eq!(element_bits_from_mangled(m), Some(32));
    }

    #[test]
    fn element_bits_rejects_unknown_type() {
        // A vector of some user-defined struct uses 'N...E' encoding.
        let m = "_ZNSt6vectorIN3foo3BarESaIS1_EEC2Ev";
        assert_eq!(element_bits_from_mangled(m), None);
    }

    #[test]
    fn element_bits_rejects_non_vector() {
        let m = "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4sizeEv";
        assert_eq!(element_bits_from_mangled(m), None);
    }

    #[test]
    fn ghost_decl_is_idempotent_in_output() {
        let mut out = String::new();
        emit_vector_ghost_decl(&mut out);
        assert!(out.contains(&format!(
            "{} <- declare_ghost_state \"{}\"",
            VECTOR_GHOST_NAME, VECTOR_GHOST_NAME
        )));
    }

    #[test]
    fn emit_push_back_couples_via_ghost() {
        let mut out = String::new();
        emit_vector_override(
            &mut out,
            StlMethod::VectorPushBackRvalue,
            32,
            "_ZNSt6vectorIjSaIjEE9push_backEOj",
            "v_pb",
            "ov_v_pb",
        );
        assert!(out.contains("llvm_ghost_value vec_back_val_ghost val"));
        assert!(out.contains("llvm_alloc (llvm_int 32)"));
    }

    #[test]
    fn emit_back_returns_alloc_with_ghost_value() {
        let mut out = String::new();
        emit_vector_override(
            &mut out,
            StlMethod::VectorBack,
            32,
            "_ZNSt6vectorIjSaIjEE4backEv",
            "v_back",
            "ov_v_back",
        );
        // Pre-state binds ghost, then execute, then post-state allocs
        // + writes + returns.
        let ghost_pos = out.find("llvm_ghost_value").expect("has ghost");
        let exec_pos = out.find("llvm_execute_func").expect("has exec");
        let alloc_pos = out.find("llvm_alloc").expect("has alloc");
        let ret_pos = out.find("llvm_return out").expect("has return");
        assert!(ghost_pos < exec_pos);
        assert!(exec_pos < alloc_pos);
        assert!(alloc_pos < ret_pos);
    }
}
