//! sret pre-state detection and the small helpers used only by
//! [`super::verify_script`].
//!
//! Extracted from `verify_script.rs` to keep that file under the
//! 500 non-whitespace line limit.

use crate::clang_ast;
use crate::constraints::{FunctionInfo, SpecConstraint, TypeInfo};
use crate::cryptol_sig;
use crate::llvm_ir::IrStructDef;
use std::collections::{HashMap, HashSet};
use std::path::Path;

// ── Small helpers used in emit_verification_script ─────────────────────────

/// Build a closure that maps `TypeInfo` to a known interface class name.
pub(super) fn make_interface_of(
    interface_classes: &HashSet<String>,
) -> impl Fn(&TypeInfo) -> Option<String> + '_ {
    move |ty: &TypeInfo| {
        if let TypeInfo::Pointer(inner) = ty {
            let name_opt = match inner.as_ref() {
                TypeInfo::Struct { name, .. } | TypeInfo::Opaque { name, .. } => {
                    Some(name.as_str())
                }
                _ => None,
            };
            if let Some(name) = name_opt {
                if interface_classes.contains(name) {
                    return Some(name.to_string());
                }
            }
        }
        None
    }
}

pub(super) fn emit_header(
    out: &mut String,
    function_name: &str,
    mangled_name: &str,
    cryptol_rel: &str,
    cryptol_fn: &str,
    needs_experimental: bool,
) {
    out.push_str(&format!(
        "// Auto-generated SAW verification script\n\
         // Function: {function_name} ({mangled_name})\n\
         // Cryptol spec: {cryptol_rel} :: {cryptol_fn}\n\
         // Generated by saw-spec-gen gen-verify\n\n",
    ));
    if needs_experimental {
        out.push_str("enable_experimental;\n\n");
    }
}

// ── sret pre-state detection ────────────────────────────────────────────────

/// How to pass sret pre-state bytes to the Cryptol model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SretPrestate {
    /// Total size of the sret buffer in bytes.
    pub buf_size: usize,
    /// Number of bytes to `take` from the full sret buffer.
    pub take_bytes: usize,
    /// Number of bytes to `drop` before taking.
    pub drop_bytes: usize,
}

/// Detect sret prestate threading by comparing the Cryptol function's
/// arity to the C++ user-arg count. Returns `Some(SretPrestate)` when
/// the Cryptol function has exactly one extra trailing `[K][8]`
/// parameter (the pre-call sret buffer bytes). When `K` equals the
/// full buffer size, `drop_bytes` is 0. When `K` is smaller, walks
/// the return struct's field layout to find the matching field offset.
pub(super) fn detect_sret_prestate(
    cryptol_spec_path: &Path,
    cryptol_fn: &str,
    target_spec: &SpecConstraint,
    target_fn: &FunctionInfo,
    ir_struct_defs: &HashMap<String, IrStructDef>,
) -> Option<SretPrestate> {
    let sig = cryptol_sig::parse_signature(cryptol_spec_path, cryptol_fn)?;
    let cpp_user_arg_count = target_spec.params.len();

    let cry_k = match cryptol_sig::detect_prestate(&sig, cpp_user_arg_count) {
        Ok(Some(n)) => {
            eprintln!(
                "  sret prestate threading: Cryptol `{cryptol_fn}` has trailing \
                 [{}][8] parameter for pre-call buffer bytes",
                n,
            );
            n
        }
        Ok(None) => return None,
        Err(e) => {
            let has_this = target_fn
                .params
                .first()
                .map(|p| p.name == "this")
                .unwrap_or(false);
            let label = if has_this {
                "instance method"
            } else {
                "free function"
            };
            eprintln!(
                "warning: sret arity mismatch for {label} `{}`:\n  {e}\n  \
                 Workaround: hand-write verify.saw or adjust the Cryptol spec.",
                target_fn.name,
            );
            return None;
        }
    };

    let ir_lookup_name: Option<String> =
        extract_alias_name(&target_spec.return_constraint.saw_type).or_else(|| {
            match &target_fn.return_type {
                TypeInfo::Struct { name, .. } | TypeInfo::Opaque { name, .. } => {
                    Some(format!("struct.{name}"))
                }
                _ => None,
            }
        });

    let buf_size = match &target_fn.return_type {
        TypeInfo::Struct {
            size_bytes: Some(n),
            ..
        } => *n,
        TypeInfo::Opaque { size_bytes, .. } if *size_bytes > 0 => *size_bytes,
        _ => {
            if let Some(ref name) = ir_lookup_name {
                let def = lookup_ir_def(name, ir_struct_defs);
                if let Some(def) = def {
                    use crate::llvm_ir::struct_types::compute_struct_size;
                    let raw_map = build_raw_ir_map(ir_struct_defs);
                    compute_struct_size(def, &raw_map).unwrap_or(0)
                } else {
                    extract_array_byte_count(&target_spec.return_constraint.saw_type).unwrap_or(0)
                }
            } else {
                extract_array_byte_count(&target_spec.return_constraint.saw_type).unwrap_or(0)
            }
        }
    };

    if buf_size == 0 {
        return Some(SretPrestate {
            buf_size: 0,
            take_bytes: cry_k,
            drop_bytes: 0,
        });
    }
    if cry_k >= buf_size {
        return Some(SretPrestate {
            buf_size,
            take_bytes: cry_k,
            drop_bytes: 0,
        });
    }

    let matches = match &target_fn.return_type {
        TypeInfo::Struct { fields, .. } => find_field_by_cpp_walk(fields, cry_k, buf_size),
        _ => Vec::new(),
    };
    let matches = if matches.is_empty() {
        ir_lookup_name
            .as_deref()
            .and_then(|name| find_field_by_ir_walk(name, cry_k, ir_struct_defs))
            .unwrap_or_default()
    } else {
        matches
    };

    match matches.len() {
        1 => {
            eprintln!("  → field at offset {} matches [{}][8]", matches[0], cry_k);
            Some(SretPrestate {
                buf_size,
                take_bytes: cry_k,
                drop_bytes: matches[0],
            })
        }
        0 => {
            eprintln!(
                "warning: Cryptol pre-state expects [{cry_k}][8] but no field \
                 of that size in return type; passing full buffer",
            );
            Some(SretPrestate {
                buf_size,
                take_bytes: cry_k,
                drop_bytes: 0,
            })
        }
        _ => {
            eprintln!(
                "warning: Cryptol pre-state expects [{cry_k}][8] — multiple \
                 fields match at offsets: {}; passing full buffer",
                matches
                    .iter()
                    .map(|o| format!("{o}"))
                    .collect::<Vec<_>>()
                    .join(", "),
            );
            Some(SretPrestate {
                buf_size,
                take_bytes: cry_k,
                drop_bytes: 0,
            })
        }
    }
}

fn extract_alias_name(saw_type: &str) -> Option<String> {
    let rest = saw_type.strip_prefix("llvm_alias \"")?;
    let name = rest.strip_suffix('"')?;
    Some(name.to_string())
}

fn extract_array_byte_count(saw_type: &str) -> Option<usize> {
    let rest = saw_type.strip_prefix("llvm_array ")?;
    let (n_str, suffix) = rest.split_once(' ')?;
    if suffix.trim() == "(llvm_int 8)" {
        n_str.parse().ok()
    } else {
        None
    }
}

fn find_field_by_cpp_walk(
    fields: &[(String, TypeInfo)],
    target_size: usize,
    buf_size: usize,
) -> Vec<usize> {
    let mut matches = Vec::new();
    let mut offset = 0usize;
    let mut walk_valid = true;
    for (fname, fty) in fields {
        if let Some((sz, align)) = clang_ast::cpp_type_size_align(fty) {
            let rem = offset % align;
            if rem != 0 {
                offset += align - rem;
            }
            if sz == target_size {
                matches.push(offset);
            }
            offset += sz;
        } else {
            let tail_known: usize = fields
                .iter()
                .skip_while(|(n, _)| n != fname)
                .skip(1)
                .filter_map(|(_, t)| clang_ast::cpp_type_size_align(t).map(|(s, _)| s))
                .sum();
            let inferred = buf_size.saturating_sub(offset).saturating_sub(tail_known);
            if inferred > 0 {
                if inferred == target_size {
                    matches.push(offset);
                }
                offset += inferred;
            } else {
                walk_valid = false;
                break;
            }
        }
    }
    if !walk_valid {
        matches.clear();
    }
    matches
}

fn find_field_by_ir_walk(
    struct_name: &str,
    target_size: usize,
    ir_defs: &HashMap<String, IrStructDef>,
) -> Option<Vec<usize>> {
    let def = lookup_ir_def(struct_name, ir_defs)?;
    let raw_map = build_raw_ir_map(ir_defs);
    let offsets = crate::llvm_ir::struct_types::field_offsets(def, &raw_map)?;
    let mut matches = Vec::new();
    for (i, field_ty) in def.fields.iter().enumerate() {
        let sz = crate::llvm_ir::struct_types::compute_ir_type_size(field_ty, &raw_map)?;
        if sz == target_size {
            matches.push(offsets[i]);
        }
    }
    Some(matches)
}

fn build_raw_ir_map(ir_defs: &HashMap<String, IrStructDef>) -> HashMap<String, IrStructDef> {
    ir_defs
        .iter()
        .flat_map(|(k, v)| {
            vec![
                (format!("%\"{k}\""), v.clone()),
                (format!("%{k}"), v.clone()),
            ]
        })
        .collect()
}

fn lookup_ir_def<'a>(
    name: &str,
    ir_defs: &'a HashMap<String, IrStructDef>,
) -> Option<&'a IrStructDef> {
    ir_defs.get(name).or_else(|| {
        let bare = name
            .strip_prefix("struct.")
            .or_else(|| name.strip_prefix("class."))
            .or_else(|| name.strip_prefix("union."))
            .unwrap_or(name);
        let suffix = format!("::{bare}");
        ir_defs
            .iter()
            .find(|(k, _)| k.ends_with(&suffix))
            .map(|(_, v)| v)
    })
}
